tweak deploy script for indexing runes on pruned node

diff --git a/deploy/setup b/deploy/setup
--- a/deploy/setup
+++ b/deploy/setup
@@ -5,16 +5,17 @@
 set -euxo pipefail
 
 CHAIN=$1
-DOMAIN=$2
-BRANCH=$3
-COMMIT=$4
-REVISION="ord-$BRANCH-$COMMIT"
+FIH=$2
+# DOMAIN=$2
+# BRANCH=$3
+# COMMIT=$4
+# REVISION="ord-$BRANCH-$COMMIT"
 
 export DEBIAN_FRONTEND=noninteractive
 
 touch ~/.hushlogin
 
-hostnamectl set-hostname $DOMAIN
+# hostnamectl set-hostname $DOMAIN
 
 apt-get install --yes \
   acl \
@@ -68,7 +69,7 @@ mkdir -p \
   /etc/systemd/system/bitcoind.service.d \
   /etc/systemd/system/ord.service.d
 
-printf "[Service]\nEnvironment=CHAIN=%s\nEnvironment=CSP_ORIGIN=%s\n" $CHAIN $CSP_ORIGIN \
+printf "[Service]\nEnvironment=CHAIN=%s\nEnvironment=CSP_ORIGIN=%s\nEnvironment=FIH=%s\n" $CHAIN $CSP_ORIGIN $FIH \
   | tee /etc/systemd/system/bitcoind.service.d/override.conf \
   > /etc/systemd/system/ord.service.d/override.conf
 
@@ -129,7 +130,7 @@ systemctl daemon-reload
 systemctl enable ord
 systemctl restart ord
 
-while ! curl --fail https://$DOMAIN/status > /dev/null; do
-  echo "Waiting for ord at https://$DOMAIN/status…"
-  sleep 1
-done
+# while ! curl --fail http://$DOMAIN/status > /dev/null; do
+#   echo "Waiting for ord at http://$DOMAIN/status…"
+#   sleep 1
+# done
